# Generated by Django 3.2.3 on 2021-06-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create',
            field=models.TimeField(),
        ),
    ]
