# Generated by Django 3.2.3 on 2021-06-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create',
        ),
    ]
