# Generated by Django 3.2.3 on 2021-06-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='last_updated_on',
            new_name='updated_at',
        ),
    ]
